### ISSUE TITLE
You did a great job. Give you some praise. I encountered a serious problem during the test

### ISSUE THREAD

**Issue by tocreator** [Harsh-Radadiya/sticker_editor#1]
You did a great job. Give you some praise. I encountered a serious problem during the test, that is, using onpanupdate to rotate doesn't work. The initial rotation is always the opposite, which is too rebellious. In addition, the X in the upper right corner, I think the user should close the operation object immediately when clicking it. At present, it needs to be operated twice

**Comment by Harsh-Radadiya** [comment]
Thank you for your valuable feedback it will resolved soon in next update.
